const DEAL_STAGES = {
  QUALIFICATION: 'Qualification',
  DISCOVERY: 'Discovery',
  PROPOSAL: 'Proposal',
  NEGOTIATION: 'Negotiation',
  WON: 'Won',
  LOST: 'Lost'
};

const CLOSED_STAGES = [DEAL_STAGES.WON, DEAL_STAGES.LOST];
const ACTIVE_STAGES = [
  DEAL_STAGES.QUALIFICATION,
  DEAL_STAGES.DISCOVERY,
  DEAL_STAGES.PROPOSAL,
  DEAL_STAGES.NEGOTIATION
];

module.exports = {
  DEAL_STAGES,
  ALL_DEAL_STAGES: Object.values(DEAL_STAGES),
  CLOSED_STAGES,
  ACTIVE_STAGES
};
